### ISSUE TITLE
Customized Key/value list Value

### ISSUE THREAD

**Issue by madmoe00** [onozaty/redmine-view-customize#109]
## Summary
We are unable to get the Actual Value of the Key/value customized list  on project level.

## Description
We have a Key/value list on project level. We are able to get the the Key only yet the Value is not showing,
ViewCustomize.context.project.customFields[0].id => 7
ViewCustomize.context.project.customFields[0].name => Client (label)
ViewCustomize.context.project.customFields[0].value=> 9 (Key on Table)

how to get the actual value of the Key/value value 

## Environment

- View customize plugin version 3.3.0
- Redmine version 5.0.3
- Ruby version 3.0.2p107
- Rails version 6.1.7.2
- Installed other plugins: additional_tags, additionals, custom_tables, redmine_ckeditor, redmine_issue_dynamic_edit, redmine_issues_tree

You can get these informations from Redmine's project page.
(E.g. http://example.com/project/test_prj1)

**Comment by onozaty** [comment]
In the case of Key/Value list, this is because they are managed by Key.
Key information is returned even when project information is retrieved via Redmine's REST API.

I do not plan to return the Value of the Key/Value list in ViewCustomize.context, so if you need the Value, you will need to write code to convert it to the Value corresponding to the Key.

Thanks.
