### ISSUE TITLE
Internal error Redmine

### ISSUE THREAD

**Issue by pilasguru** [onozaty/redmine-view-customize#26]
Redmine show an internal error as soon as I install `redmine-view-customize`

Here is the `log/production.log

```
Started GET "/" for 10.0.2.2 at 2018-09-06 20:47:14 +0000
Processing by WelcomeController#index as HTML
  Current user: admin (id=1)
  Rendered welcome/index.html.erb within layouts/base (2.2ms)
Completed 500 Internal Server Error in 52ms (ActiveRecord: 3.1ms)

ActionView::Template::Error (undefined method `all' for ViewCustomize:Module):
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: <!-- page specific tags -->
    18: <%= yield :header_tags -%>
    19: </head>
  plugins/redmine-view-customize/lib/view_customize/view_layouts_base_html_head_hook.rb:17:in `match_customize'
  plugins/redmine-view-customize/lib/view_customize/view_layouts_base_html_head_hook.rb:5:in `view_layouts_base_html_head'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:16:in `_app_views_layouts_base_html_erb___774233765271934486_47005662821820'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

Do you have any suggestion?

**Comment by peney83** [comment]
hi @onozaty 
I install the plugin with the version 1.2.0, it cause the Redmine do not work and show an internal error. The problem is the same as above . the log is 

Rendered news/_news.html.erb (12.4ms)
  Rendered welcome/index.html.erb within layouts/base (132.2ms)
  Rendered plugins/advanced_roadmap/app/views/hooks/_stylesheet.html.erb (1.0ms)
  Rendered plugins/redmine_code_review/app/views/code_review/_html_header.html.erb (1.3ms)
  Rendered plugins/scrum/app/views/scrum_hooks/_head.html.erb (1.1ms)
Completed 500 Internal Server Error in 569ms (ActiveRecord: 15.5ms)

ActionView::Template::Error (undefined method `roles' for #<User:0x0055bdfd8e4868>):
    17: <script type="text/javascript" src="/chartkick/Chart.bundle.min.js"></script>
    18: <%= javascript_heads %>
    19: <%= heads_for_theme %>
    20: <%= call_hook :view_layouts_base_html_head %>
    21: 
    22: <%= yield :header_tags -%>
    23: </head>
  plugins/view_customize/lib/view_customize/view_hook.rb:82:in `create_view_customize_context'
  plugins/view_customize/lib/view_customize/view_hook.rb:10:in `view_layouts_base_html_head'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/layouts/base.html.erb:20:in `_app_views_layouts_base_html_erb___3024194164021486896_47137250057600'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in `call'

**Comment by onozaty** [comment]
Close as it duplicates below.
* https://github.com/onozaty/redmine-view-customize/issues/29
